### ISSUE TITLE
Cannot view cacheflag in Control panel - production

### ISSUE THREAD

**Issue by CreateSean** [mmikkel/CacheFlag-Craft3#17]
I can view the cacheflag cp page locally however on production the cacheflag cp page is missing. This is for superadmins and regular users who have permissions set to view the cacheflag cp page.

Please advise.

Craft 3.7.37
Cacheflag 1.3.1

**Comment by mmikkel** [comment]
I assume you have the `allowAdminChanges` config setting set to `false` in production? 

Since the cache flags are synced using the project config, [Cache Flag's CP section is only available in environments where admin changes are allowed](https://github.com/mmikkel/CacheFlag-Craft3#project-config-and-allowadminchanges).

If you need to clear any flagged caches in production, that's doable either via the native clear caches utility, or via the `php craft invalidate-tags/cacheflag` CLI command (more info [here](https://github.com/mmikkel/CacheFlag-Craft3#invalidating-flagged-caches))

**Comment by CreateSean** [comment]
thank you.

Is there anyway to have the option to clear caches in the control panel with allowadminchanges set to false. Client wants to be able to do this on their own.

**Comment by mmikkel** [comment]
Yes, via the native Clear Caches utility:

![CleanShot 2022-08-02 at 21 08 45@2x](https://user-images.githubusercontent.com/298510/182454170-3585da37-b4e4-4b99-9c76-00da00938754.png)

_Shameless plug: the [CP Clear Cache plugin](https://plugins.craftcms.com/cp-clearcache?craft4) provides quicker/easier access to the clear caches utility._

I realise that giving clients full access to the clear caches utility might not be ideal in all circumstances, but it's the best I can do for right now. Marking this issue as a feature request though :)

**Comment by mmikkel** [comment]
Resolved in [Cache Flag 1.4.0](https://github.com/mmikkel/CacheFlag-Craft3/releases/tag/1.4.0) 🎉 

Cache Flag's CP section is now available in all environments. In environments where admin changes are disallowed, saving/changing flags isn't possible, but invalidating them is.
