### ISSUE TITLE
Solspace Calendar

### ISSUE THREAD

**Issue by Moorst** [mmikkel/CacheFlag-Craft3#4]
Great to see this plugin on Craft 3!

I have a site using the [Calendar plugin](https://solspace.com/craft/calendar/) to manage events and noticed this element type isn't appearing on the Cache Flag settings page. 

Is it possible to pick this up? It's registered as Solspace\Calendar\Elements\Event.

**Comment by mmikkel** [comment]
That should be doable @Moorst – I'll take a look at it ASAP. Also, pull requests are super yummy, if you'd want to take a stab at it yourself ;)

**Comment by bfopma** [comment]
+1 on this feature request!

**Comment by mmikkel** [comment]
Forgot to update this issue, but for posterity: 

Cache Flag uses `Craft::$app->getElements()->getAllElementTypes()` to output cache flag input fields for all registered element types. If the Solspace `Event` element type doesn't appear, that likely means that the Calendar plugin isn't using the `EVENT_REGISTER_ELEMENT_TYPES` event to register that custom element type, so this is something that will need to be fixed by Solspace.
